### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dayvsonlima** [dayvsonlima/webinc#1]
- [ ] Write README.md
- [ ] Create Log Helper
- [ ] Create Request Header Vars Helper
